zookeeper:
 build: zookeeper 
 ports: 
   - "2181:2181"
 
kafka:
 build: kafka
 ports:
  - "9092:9092"
 links:
  - zookeeper

redis:
 build: redis
 ports: 
  - "6379:6379"

zabbix:
 build: zabbix
 ports:
  - "10051:10051"
  - "80:80"
